### ISSUE TITLE
Why are the log levels inconsistent here?

### ISSUE THREAD

**Issue by yaming116** [ioBroker/ioBroker.ham#30]
https://github.com/ioBroker/ioBroker.ham/blob/bb20855704c4258760c169b66f5b4802aee4643b/main.js#L192

**Comment by Apollon77** [comment]
Because the wrapper library is using logging starting with "debug" as most detailed level. But ioBroker uses "silly" as the most detailed ... and based on needs the logging levels are mapped between iobroker and the library.
So for adapter in ioBroker with logging info normally you do not want to see anything, but the library is logging is default status as info ... so mapping is needed
