### ISSUE TITLE
Feature request: delete homebridge cache

### ISSUE THREAD

**Issue by yaming116** [ioBroker/ioBroker.ham#31]
When I delete the ham instance, the homebridge's cache is not deleted.
* `iobroker-data/ham_x/persist`
*  `iobroker-data/ham_x/accessories`

When the username in the bridge changes, the homekit will not be able to search for the current bridge.
Can we also delete the relevant cache when deleting ham or run the current configuration and change the local cache before changing

**Comment by Apollon77** [comment]
Hm ... good catch. I need to check how to achieve that.

**Comment by Apollon77** [comment]
Hm ... ioBroker is not deleting the directory on deletion ofg an instance because it could not wanted  by the user, so also detelting on instance creation is not ideal.

One idea could be to read the persist/Accessory_Info.json and compare the pin code to the current one, but the "username" is not included there in a readable way.

The other option would be to offer a checkbox in Admin "cleasr Homebridge cache" to be shown for local mode and when you click and save it will clear the directory.

What do you think?

**Comment by yaming116** [comment]
Whether we can handle this work automatically, most people don't understand the meaning of this option and the effect it produces. I think we can first check if the corresponding directory 'config.json` exists, and then read the historical version of `username` for comparison.
what do you think?

**Comment by Apollon77** [comment]
The problem is that the adapter will overwrite the config.json for local mode on start, but yes this could be included before doing that ... I will have a look.
But in fact also then all states will become invalid and "doubled" because all accessories get new IDs, correct? So should we also kill all objects and states in this case?

**Comment by Apollon77** [comment]
First implemented and availabel on GitHub now is: Removal of cache dir on username change for local mode. Please give it a try

**Comment by yaming116** [comment]
Good news. I'll test it right now

**Comment by yaming116** [comment]
It’s ok now, I will do more testing.
