### ISSUE TITLE
Admin-Tab blank page

### ISSUE THREAD

**Issue by Tyraenor** [ioBroker/ioBroker.ham#352]
Hi,

I try to load the Admin-Tab for ham. But it is only a blank page.

Do I need to configure it somehow?

Thanks.

Regards

**Comment by Draexl** [comment]
Same

**Comment by Apollon77** [comment]
Do you get any error in your browser error log?

**Comment by Draexl** [comment]
I think it's a browser problem. Chrome works, Safari not.

**Comment by RP70DP** [comment]
Same here with Firefox and Edge.

**Comment by Apollon77** [comment]
Hm ... 3 users have the issue and noone checks what I ask for? Then it seems you want to help, also fine ...

For the case you overlooked my question:

> Do you get any error in your browser error log?

**Comment by RP70DP** [comment]
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.0.202:8081/adapter/ham/build/tab.js
Source-Map-Adresse: /tab.js.map

**Comment by RP70DP** [comment]
After searching for tuya:
XHR GET https://api.npms.io/v2/search?q=keywords:homebridge-plugin tuya&from=0&size=100

Status
500
Internal Server Error
VersionHTTP/3
Übertragen1,15 KB (53 B Größe)
Referrer Policystrict-origin-when-cross-origin

**Comment by Apollon77** [comment]
Both should not cause an empty page ...

**Comment by RP70DP** [comment]
Then the answer to your question is: No.

**Comment by ninja-warrior** [comment]
Same here.

**Comment by ninja-warrior** [comment]
Likely possible, that I found the reason for the empty admin page. Before showing the content of the admin page there is a script calling the following api to get a list of available plugins:

https://api.npms.io/v2/search?q=keywords:homebridge-plugin&from=0&size=100

The api call is not valid, so that it returns the error code 500. Details, refer to API documentation: https://api-docs.npms.io/

If I call the api with the link below, I receive a list of available plugins:

https://api.npms.io/v2/search?q=keywords:homebridge-plugin

Best regards,
David

**Comment by Apollon77** [comment]
Cool, will check the next days ... so npm changed something :-)

**Comment by ninja-warrior** [comment]
Any updates?

**Comment by Apollon77** [comment]
No because I was on vacation ... it is on the list and I will see when I come to it ... sorry. The alternative setup options is to enter the package names in the main adapter config and add json as config manually

**Comment by Apollon77** [comment]
fixed in 5.0.1 already
